### ISSUE TITLE
SyntaxError: future feature annotations is not defined

### ISSUE THREAD

**Issue by jlchulilla** [Blasterai/codaio#18]
Hi, Mijail

Before all, thanks for all your efforts!

Now, I have tried to test your examples. I installed your library with pip, and when I tried to run this code:

```
from codaio import Coda, Document

coda = Coda('APIKEY')

doc = Document.from_environment('DOCID')

doc.list_tables()
```

I have obtained this error

```
Traceback (most recent call last):
  File "primertestapi.py", line 1, in <module>
    from codaio import Coda, Document
  File "/usr/local/lib/python3.6/dist-packages/codaio/__init__.py", line 1, in <module>
    from .coda import Coda, Document, Table, Row, Column, Cell
  File "/usr/local/lib/python3.6/dist-packages/codaio/coda.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

What can I do?

Thanks in advance!

**Comment by licht1stein** [comment]
@jlchulilla what's your python version?

**Comment by jlchulilla** [comment]
3.6.7

**Comment by jlchulilla** [comment]
Hi? Any news?

**Comment by jlchulilla** [comment]
Hi?

**Comment by jlchulilla** [comment]
Hi?

**Comment by licht1stein** [comment]
hi sorry about the long wait time, was too busy. I'll look into it.

**Comment by licht1stein** [comment]
@jlchulilla it looks like you're running a python version prior to `annotations` introduction. What's your python version?
