### ISSUE TITLE
Table.rows() failing on JSONDecodeError 

### ISSUE THREAD

**Issue by piotrcichosz** [Blasterai/codaio#52]
>>> table = doc.get_table('grid-1_QJEqPX5n')
>>> table
Table(name='MainTable')
>>> table.rows()[0]
Row(name='some row.. index=212)

>>> rows=table.rows()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/codaio/coda.py", line 877, in rows
    for i in self.document.coda.list_rows(
  File "/usr/local/lib/python3.9/site-packages/codaio/coda.py", line 481, in list_rows
    return self.get(
  File "<decorator-gen-2>", line 2, in get
  File "/usr/local/lib/python3.9/site-packages/codaio/coda.py", line 37, in handle_response
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/codaio/coda.py", line 126, in get
    while r.json().get("nextPageLink"):
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by pyatasya** [comment]
Same problem, we're also affected. Anyone has an idea of how to fix?

**Comment by licht1stein** [comment]
Please make a public document with a similar table for me to investigate.
